kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "petstore-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/mdiwing/ericsson-demo.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipeline/Jenkinsfile

apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: petstore-publish-api-pipeline
metadata:
  annotations:
    description: 3scale API publishing Pipeline
  name: petstore-publish-api-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: petstore-publish-api-pipeline
    name: petstore-publish-api-pipeline
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: None
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: pipeline/Jenkinsfile
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: DEV_PRIVATE_BASE_URL
          value: ${DEV_PRIVATE_BASE_URL}
        - name: PROD_PRIVATE_BASE_URL
          value: ${PROD_PRIVATE_BASE_URL}
        - name: API_BASE_SYSTEM_NAME
          value: ${API_BASE_SYSTEM_NAME}
        - name: DEV_PROJECT
          value: ${DEV_PROJECT}
        - name: DEV_PROJECT
          value: ${DEV_PROJECT}
        - name: PROD_PROJECT
          value: ${PROD_PROJECT}
        - name: IMAGE_NAMESPACE
          value: ${IMAGE_NAMESPACE}
        - name: SECRET_NAME
          value: ${SECRET_NAME}
        - name: TARGET_INSTANCE_DEV
          value: ${TARGET_INSTANCE_DEV}
        - name: TARGET_INSTANCE_PROD
          value: ${TARGET_INSTANCE_PROD}
        - name: DEV_DEVELOPER_ACCOUNT_ID
          value: ${DEV_DEVELOPER_ACCOUNT_ID}
        - name: PROD_DEVELOPER_ACCOUNT_ID
          value: ${PROD_DEVELOPER_ACCOUNT_ID}
        - name: DISABLE_TLS_VALIDATION
          value: ${DISABLE_TLS_VALIDATION}
        - name: APPLICATION_NAME
          value: ${APPLICATION_NAME}
        - name: OPENAPI_SPECIFICATION_FILE
          value: ${OPENAPI_SPECIFICATION_FILE}
        - name: TOOLBOX_IMAGE_REGISTRY
          value: ${TOOLBOX_IMAGE_REGISTRY}
parameters:
- name: GIT_REPO
  value: https://github.com/mdiwing/ericsson-demo.git
  required: true
- name: GIT_BRANCH
  value: master
  required: true
- name: PUBLIC_BASE_PATH
  required: true
  value: "/api"
- name: API_BASE_SYSTEM_NAME
  value: petstore
  required: true
- name: DEV_PRIVATE_BASE_URL
- name: DEV_PROJECT
  required: true
  value: petstore-api-dev
- name: DEV_PROJECT
  required: true
  value: petstore-api-test
- name: PROD_PRIVATE_BASE_URL
- name: PROD_PROJECT
  required: true
  value: petstore-api-prod
- name: IMAGE_NAMESPACE
  required: true
  value: petstore
- name: SECRET_NAME
  value: 3scale-toolbox
  required: true  
- name: TARGET_INSTANCE_DEV
  value: 3scale-tenant-groupit
  required: true  
- name: TARGET_INSTANCE_PROD
  value: petstore-prod
  required: true
- name: DEV_DEVELOPER_ACCOUNT_ID
  required: true
  value: "5"
- name: PROD_DEVELOPER_ACCOUNT_ID
  required: true
  value: "7"
- name: DISABLE_TLS_VALIDATION
  value: "yes"
- name: APPLICATION_NAME
  value: "petstore-api"
  required: true
- name: OPENAPI_SPECIFICATION_FILE
  required: true
  value: "open-api/petstore-openapi-spec.json"
- name: TOOLBOX_IMAGE_REGISTRY
  required: true
  value: "registry.redhat.io/3scale-amp2/toolbox-rhel7:3scale2.7"
