apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: threescale-api-publish-pipeline
metadata:
  annotations:
    description: 3scale API publishing Pipeline
  name: threescale-api-publish-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: threescale-api-publish-pipeline
    name: threescale-api-publish-pipeline
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: None
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: pipeline/Jenkinsfile
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: DEV_PRIVATE_BASE_URL
          value: ${DEV_PRIVATE_BASE_URL}
        - name: TEST_PRIVATE_BASE_URL
          value: ${TEST_PRIVATE_BASE_URL}
        - name: PROD_PRIVATE_BASE_URL
          value: ${PROD_PRIVATE_BASE_URL}
        - name: API_BASE_SYSTEM_NAME
          value: ${API_BASE_SYSTEM_NAME}
        - name: DEV_PROJECT
          value: ${DEV_PROJECT}
        - name: TEST_PROJECT
          value: ${TEST_PROJECT}
        - name: PROD_PROJECT
          value: ${PROD_PROJECT}
        - name: IMAGE_NAMESPACE
          value: ${IMAGE_NAMESPACE}
        - name: SECRET_NAME
          value: ${SECRET_NAME}
        - name: TARGET_INSTANCE_DEV
          value: ${TARGET_INSTANCE_DEV}
        - name: TARGET_INSTANCE_TEST
          value: ${TARGET_INSTANCE_TEST}
        - name: TARGET_INSTANCE_PROD
          value: ${TARGET_INSTANCE_PROD}
        - name: DISABLE_TLS_VALIDATION
          value: ${DISABLE_TLS_VALIDATION}
        - name: APPLICATION_NAME
          value: ${APPLICATION_NAME}
        - name: APPLICATION_GIT_CONTEXT_DIR
          value: ${APPLICATION_GIT_CONTEXT_DIR}
        - name: OPENAPI_SPECIFICATION_FILE
          value: ${OPENAPI_SPECIFICATION_FILE}
        - name: DEV_DEVELOPER_ACCOUNT_ID
          value: ${DEV_DEVELOPER_ACCOUNT_ID} 
        - name: TEST_DEVELOPER_ACCOUNT_ID
          value: ${TEST_DEVELOPER_ACCOUNT_ID}
        - name: PROD_DEVELOPER_ACCOUNT_ID
          value: ${PROD_DEVELOPER_ACCOUNT_ID}
        - name: APPLICATION_PLAN
          value: ${APPLICATION_PLAN}
        - name: TOOLBOX_IMAGE_REGISTRY
          value: ${TOOLBOX_IMAGE_REGISTRY}
parameters:
- name: GIT_REPO
  value: https://github.com/mdiwing/ericsson-demo.git
  required: true
- name: GIT_BRANCH
  value: master
  required: true
- name: PUBLIC_BASE_PATH
  required: true
  value: "/"
- name: API_BASE_SYSTEM_NAME
  value: petstore
  required: true
- name: DEV_PRIVATE_BASE_URL
  value: "http://petstore-dev.petstore-dev.svc.cluster.local:8080"
  required: true
- name: DEV_PROJECT
  required: true
  value: petstore-dev
- name: TEST_PRIVATE_BASE_URL
  value: "http://petstore-test.petstore-test.svc.cluster.local:8080"
  required: true
- name: TEST_PROJECT
  required: true
  value: petstore-test
- name: PROD_PRIVATE_BASE_URL
  value: "http://petstore-prod.petstore-prod.svc.cluster.local:8080"
  required: true
- name: PROD_PROJECT
  required: true
  value: petstore-prod
- name: IMAGE_NAMESPACE
  required: true
  value: petstore
- name: SECRET_NAME
  value: 3scale-toolbox
  required: true  
- name: TARGET_INSTANCE_DEV
  value: 3scale-tenant-groupit
  required: true  
- name: TARGET_INSTANCE_TEST
  value: 3scale-tenant-santools
  required: true
- name: TARGET_INSTANCE_PROD
  value: 3scale-tenant-managed-services
  required: true
- name: DISABLE_TLS_VALIDATION
  value: "yes"
- name: APPLICATION_NAME
  value: "petstore"
  required: true
- name: APPLICATION_GIT_CONTEXT_DIR
  value: "demo-apps/petstore"
  required: true
- name: DEV_DEVELOPER_ACCOUNT_ID
  value: "6"
  required: true
- name: TEST_DEVELOPER_ACCOUNT_ID
  value: "8"
  required: true
- name: PROD_DEVELOPER_ACCOUNT_ID
  value: "10"
  required: true
- name: OPENAPI_SPECIFICATION_FILE
  required: true
  value: "pipeline/openapi-spec.json"
- name: APPLICATION_PLAN
  value: "https://raw.githubusercontent.com/mdiwing/ericsson-demo/master/pipeline/application-plan.yml"
  required: true
- name: TOOLBOX_IMAGE_REGISTRY
  required: true
  value: "registry.redhat.io/3scale-amp2/toolbox-rhel7:3scale2.7"
